name: Gitleaks Secret Scan

on:
  pull_request:
    branches: [ "main" ]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          args: "--no-git --source=. --verbose --redact --exit-code 1"
